### ISSUE TITLE
HtmElement doesn't work with Selenium java-bindings 3.5.1

### ISSUE THREAD

**Issue by doctordrue** [yandex-qatools/htmlelements#139]
Invocation target exception throws when calling
`PageFactory.initElements(new HtmlElementDecorator(new HtmlElementLocatorFactory(driver)), this);`

Stack-trace:
```
Caused by: java.lang.NoSuchMethodError: ru.yandex.qatools.htmlelements.loader.decorator.HtmlElementFieldAnnotationsHandler.buildByFromFindBy(Lorg/openqa/selenium/support/FindBy;)Lorg/openqa/selenium/By;
	at ru.yandex.qatools.htmlelements.loader.decorator.HtmlElementFieldAnnotationsHandler.buildByFromFindAnnotations(HtmlElementFieldAnnotationsHandler.java:49)
	at ru.yandex.qatools.htmlelements.loader.decorator.HtmlElementFieldAnnotationsHandler.buildByFromHtmlElementAnnotations(HtmlElementFieldAnnotationsHandler.java:57)
	at ru.yandex.qatools.htmlelements.loader.decorator.HtmlElementFieldAnnotationsHandler.buildBy(HtmlElementFieldAnnotationsHandler.java:28)
	at org.openqa.selenium.support.pagefactory.DefaultElementLocator.<init>(DefaultElementLocator.java:58)
	at org.openqa.selenium.support.pagefactory.AjaxElementLocator.<init>(AjaxElementLocator.java:58)
	at org.openqa.selenium.support.pagefactory.AjaxElementLocator.<init>(AjaxElementLocator.java:53)
	at ru.yandex.qatools.htmlelements.loader.decorator.HtmlElementLocatorFactory.createLocator(HtmlElementLocatorFactory.java:35)
	at ru.yandex.qatools.htmlelements.loader.decorator.HtmlElementDecorator.decorateWebElement(HtmlElementDecorator.java:93)
	at ru.yandex.qatools.htmlelements.loader.decorator.HtmlElementDecorator.decorateTypifiedElement(HtmlElementDecorator.java:79)
	at ru.yandex.qatools.htmlelements.loader.decorator.HtmlElementDecorator.decorate(HtmlElementDecorator.java:55)
	at org.openqa.selenium.support.PageFactory.proxyFields(PageFactory.java:113)
	at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:105)
```

**Comment by doctordrue** [comment]
It seems org.openqa.selenium.support.pagefactory.AbstractAnnotations.buildByFromFindBy(FindBy) has been removed in Selenium 3.5.1

**Comment by mgrybyk** [comment]
yes, does anyone know how to fix it?

P.S.
https://github.com/SeleniumHQ/selenium/commit/0b3018895b4cd1f6e7f398b98ecc8ce4cdd877a3

**Comment by mgrybyk** [comment]
@doctordrue you have missed one issue with HtmlElementClassAnnotationsHandler


-                return buildByFromFindBy(clazz.getAnnotation(FindBy.class));
+                return new FindBy.FindByBuilder().buildIt(clazz.getAnnotation(FindBy.class), null);

**Comment by mgrybyk** [comment]
sorry, missed your another commit
https://github.com/yandex-qatools/htmlelements/pull/140/commits/fbd6da292f670550cd9c266b589433f1b46368b9

**Comment by doctordrue** [comment]
@lanwen, Is anybody going to take care about deploying new version to mavem-central. It seems there is a problem with deploying job due to SonarQube server inaccessibility: http://ci.qatools.ru/job/htmlelements_master-deploy/40/

**Comment by lanwen** [comment]
@doctordrue Forgot to press the "release" button in sonatype. Sorry for that. Should sync now in few hours

**Comment by lanwen** [comment]
Closed via #139
